### ISSUE TITLE
Question about code

### ISSUE THREAD

**Issue by jinyongyoo** [nng555/ssmba#1]
Hi, I would like to use SSMBA to perform data augmentation and I've been looking over the code to make sense of it. I noticed that the `hf_masked_encode` function returns corrupted tokens and binary vector `mask` indicating whether the token has been corrupted or not. But I'm seeing that the binary mask tensor is then passed as the second argument for `hf_reconstruction_prob_tok`, but I'm having a hard time seeing how this is supposed to be the `target_tokens`. I'm assuming `target_tokens` are the original tokens before the corruption step, so it makes no sense to me why we're suddenly passing the binary mask.

I also noticed that you create a variable named `mask_targets` (https://github.com/nng555/ssmba/blob/2e98bccdcd621848ab6e0441789f7a07a28bdd51/utils.py#L38) but never use it afterwards.

**Comment by nng555** [comment]
You're right, looks like `mask_targets` is some leftover code from a different version of the function. 

`target_tokens` is supposed to be a mask tensor where the masked values are the original target values. For example, an original sentence [5, 3, 8, 10] might be masked to [5, 3, 8, <mask>] with a corresponding `target_tokens` of [<pad>, <pad>, <pad>, 10]. Since the actual target values aren't used anywhere in the reconstruction function, simply passing in a binary mask of [0, 0, 0, 1] actually works the same, since the <pad> token is usually 0. 

I've fixed this bug and things should work correctly now.
