### ISSUE TITLE
Question about tokenization/masking schemes

### ISSUE THREAD

**Issue by ethch18** [nng555/ssmba#3]
Hi, thanks for making your code available!  Had some questions about implementation details in your paper and didn't see a contact email there, so I hope it's okay if I open an issue here.

I'm looking at applying SSMBA in the context of a sequence tagging task, where maintaining tokenization is pretty important for the label-preservation setup (and, to a lesser extent, the other two setups).  I'm wondering about your masking and detokenization process, and whether you impose any constraints there.  Since *BERT models use subword tokenization, it seems like randomly masking out tokens could lead to only part of a word being masked out.  More generally, it also seems like masking out suffixes/prefixes would yield pretty similar data to what was originally there, or perhaps introduce another word.  Are there any checks to make sure that masking and filling a proper subword results in another proper subword that fits back in with the rest of the word?  Alternatively, are there ways to ensure only entire words are masked out, so that full new words can be inserted?

Thanks!

**Comment by nng555** [comment]
There are currently no constraints on tokenization/detokenization (which are both handled by the huggingface libraries). Currently I do not have an option for whole word masking but I might add it soon. 

There are no checks to make sure masked out subwords correspond correctly (although implicitly BERT handles this as it will assign low probability to tokens that would not complete subwords properly). This didn't seem to matter much during experiments since even augmented sentences with nonsense or garbage tokens still improved training.

**Comment by ethch18** [comment]
I see, thanks for your response!

I also wanted to clarify how you trained with the soft labels -- did you use the soft label distributions from the teacher model for all sentences (incl. the original labeled data), or were there cases where you used the hard gold labels for the original data?

**Comment by nng555** [comment]
Most of the time we used soft labels. In a few cases we used hard labels generated from the model or preserved the original gold labels. Refer to the appendix for a list of specific hyperparameters used for each dataset.

**Comment by ethch18** [comment]
Thanks for your reply -- I meant to ask whether there were ever cases where you trained a given model jointly on soft and hard labels, but from your description it seems like that's not the case?

**Comment by nng555** [comment]
No, at least not on the augmented examples.

**Comment by ethch18** [comment]
Thanks!
